name: Build & Release Electron App

on:
  push:
    tags:
      - "v*.*.*"   # e.g. v1.0.0
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write   # REQUIRED for GitHub Releases

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # -------------------------
      # Windows code signing
      # -------------------------
      - name: Detect Windows code signing
        id: win-signing
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          if ("${{ secrets.WIN_CSC_BASE64 }}" -ne "") {
            echo "enabled=true" >> $env:GITHUB_OUTPUT
            Write-Host "Windows code signing ENABLED"
          } else {
            echo "enabled=false" >> $env:GITHUB_OUTPUT
            Write-Host "Windows code signing DISABLED (no cert)"
          }

      - name: Install Windows signing certificate
        if: matrix.os == 'windows-latest' && steps.win-signing.outputs.enabled == 'true'
        shell: powershell
        run: |
          $bytes = [Convert]::FromBase64String("${{ secrets.WIN_CSC_BASE64 }}")
          [IO.File]::WriteAllBytes("codesign.pfx", $bytes)
          Write-Host "Code signing certificate written"

      # -------------------------
      # Build & publish (Windows)
      # -------------------------
      - name: Build and publish (Windows)
        if: matrix.os == 'windows-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: codesign.pfx
          CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_PASSWORD }}
        run: npm run build

      # -------------------------
      # Build & publish (macOS)
      # -------------------------
      - name: Build and publish (macOS)
        if: matrix.os == 'macos-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
          CSC_NAME: ${{ secrets.MAC_CSC_NAME }}
        run: npm run build

      # -------------------------
      # Build & publish (Linux)
      # -------------------------
      - name: Build and publish (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build
